import { Grant, DeadlineAlert, WatchlistItem, ScanningAlert, ProjectProfile } from './types';

export const projectProfile: ProjectProfile = {
  name: 'RMD26',
  description: 'Autonomous Global Grant-Search Agent operating continuously',
  focus: ['AI/ML', 'autonomous agents', 'cloud', 'SaaS', 'digital compliance'],
  technicalReadinessLevel: 7,
  budget: 5000000,
  regions: ['EU', 'US', 'UK', 'Asia'],
  sectors: ['FinTech', 'Digital', 'Innovation'],
};

export const mockGrants: Grant[] = [
  {
    id: 'grant_001',
    name: 'Horizon Europe - AI & Digital Sovereignty',
    region: 'EU',
    country: 'Belgium',
    fundingAmount: 2500000,
    deadline: '2024-06-15',
    eligibility: ['EU Member States', 'Associated Countries', 'Private Companies'],
    supportedThemes: ['AI/ML', 'Digital Sovereignty', 'Cloud Computing'],
    officialSourceLink: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/',
    fitScore: 92,
    reasonForRelevance: 'Perfect alignment with autonomous agents and AI focus',
    submissionStatus: 'in_progress',
    createdAt: '2024-04-01',
    updatedAt: '2024-04-10',
  },
  {
    id: 'grant_002',
    name: 'Digital Europe Programme - Infrastructure for AI',
    region: 'EU',
    country: 'Luxembourg',
    fundingAmount: 1800000,
    deadline: '2024-05-30',
    eligibility: ['EU Entities', 'Public Bodies', 'Research Institutions'],
    supportedThemes: ['AI Infrastructure', 'Digital Transformation', 'Data Management'],
    officialSourceLink: 'https://digital-strategy.ec.europa.eu/en/funding',
    fitScore: 88,
    reasonForRelevance: 'Strong focus on AI infrastructure and cloud solutions',
    submissionStatus: 'not_started',
    createdAt: '2024-04-05',
    updatedAt: '2024-04-10',
  },
  {
    id: 'grant_003',
    name: 'NSF SBIR Phase II - AI for Autonomous Systems',
    region: 'US',
    country: 'United States',
    fundingAmount: 1000000,
    deadline: '2024-07-20',
    eligibility: ['US Small Businesses', 'VC-Backed Companies'],
    supportedThemes: ['AI', 'Autonomous Systems', 'R&D'],
    officialSourceLink: 'https://www.nsf.gov/sbir/',
    fitScore: 85,
    reasonForRelevance: 'Excellent match for autonomous agent technology',
    submissionStatus: 'not_started',
    createdAt: '2024-04-08',
    updatedAt: '2024-04-10',
  },
  {
    id: 'grant_004',
    name: 'EIC Accelerator - Deep Tech AI',
    region: 'EU',
    country: 'Austria',
    fundingAmount: 3000000,
    deadline: '2024-05-15',
    eligibility: ['Startups', 'SMEs', 'Scale-ups'],
    supportedThemes: ['Deep Tech', 'AI', 'Enterprise SaaS'],
    officialSourceLink: 'https://eic.ec.europa.eu/',
    fitScore: 95,
    reasonForRelevance: 'Exceptional fit for scaling AI-powered compliance solutions',
    submissionStatus: 'submitted',
    createdAt: '2024-04-02',
    updatedAt: '2024-04-10',
  },
  {
    id: 'grant_005',
    name: 'UK Innovation & Tech Strategy - AI Leaders',
    region: 'UK',
    country: 'United Kingdom',
    fundingAmount: 1500000,
    deadline: '2024-06-28',
    eligibility: ['UK Companies', 'Tech Leaders', 'AI Innovators'],
    supportedThemes: ['AI', 'Innovation', 'Digital Compliance'],
    officialSourceLink: 'https://www.innovateuk.org/',
    fitScore: 82,
    reasonForRelevance: 'Good alignment with UK innovation ecosystem',
    submissionStatus: 'not_started',
    createdAt: '2024-04-09',
    updatedAt: '2024-04-10',
  },
];

export const mockDeadlines: DeadlineAlert[] = [
  {
    grantId: 'grant_004',
    grantName: 'EIC Accelerator - Deep Tech AI',
    deadline: '2024-05-15',
    daysUntilDeadline: 35,
    priority: 'critical',
  },
  {
    grantId: 'grant_002',
    grantName: 'Digital Europe Programme - Infrastructure for AI',
    deadline: '2024-05-30',
    daysUntilDeadline: 50,
    priority: 'critical',
  },
  {
    grantId: 'grant_001',
    grantName: 'Horizon Europe - AI & Digital Sovereignty',
    deadline: '2024-06-15',
    daysUntilDeadline: 66,
    priority: 'high',
  },
  {
    grantId: 'grant_005',
    grantName: 'UK Innovation & Tech Strategy - AI Leaders',
    deadline: '2024-06-28',
    daysUntilDeadline: 79,
    priority: 'medium',
  },
  {
    grantId: 'grant_003',
    grantName: 'NSF SBIR Phase II - AI for Autonomous Systems',
    deadline: '2024-07-20',
    daysUntilDeadline: 101,
    priority: 'low',
  },
];

export const mockWatchlist: WatchlistItem[] = [
  {
    grantId: 'grant_001',
    grantName: 'Horizon Europe - AI & Digital Sovereignty',
    reason: 'Strategic opportunity for 2025 call',
    addedAt: '2024-03-15',
    priority: 'strategic',
  },
  {
    grantId: 'grant_004',
    grantName: 'EIC Accelerator - Deep Tech AI',
    reason: 'Backup option if current submission rejected',
    addedAt: '2024-04-01',
    priority: 'backup',
  },
];

export const mockAlerts: ScanningAlert[] = [
  {
    id: 'alert_001',
    type: 'new_grant',
    grantName: 'EIC Accelerator - Deep Tech AI',
    message: 'New high-fit grant opportunity detected: EIC Accelerator with 95% fit score',
    createdAt: '2024-04-10T10:30:00Z',
    read: false,
  },
  {
    id: 'alert_002',
    type: 'deadline_approaching',
    grantName: 'EIC Accelerator - Deep Tech AI',
    message: 'Critical deadline in 35 days - Recommend starting proposal',
    createdAt: '2024-04-10T09:15:00Z',
    read: false,
  },
  {
    id: 'alert_003',
    type: 'evaluation_complete',
    grantName: 'Horizon Europe - AI & Digital Sovereignty',
    message: 'Grant evaluation complete - 92% fit score, GO decision recommended',
    createdAt: '2024-04-09T14:45:00Z',
    read: true,
  },
];
